* `circuit.Package` `gplugins.klayout.example`
* Generated by `vlsirtools.SpiceNetlister`
*

.SUBCKT straight_L392_N2_CSmetal3_W10
+ 1
* No parameters

.ENDS

.SUBCKT straight_L200_N2_CSmetal3_W10
+ 1
* No parameters

.ENDS

.SUBCKT straight_L8_N2_CSmetal3_W10
+ 1
* No parameters

.ENDS

.SUBCKT wire_corner_CSmetal3_RNone
+ 1
* No parameters

.ENDS

.SUBCKT straight_L400_N2_CSmetal3_W10
+ 1
* No parameters

.ENDS

.SUBCKT pad_S100_100_LMTOP_BLNo_fdaf576b
+ 1 2
* No parameters

.ENDS

.SUBCKT pads_correct_Ppad_CSmetal3
* No ports
* No parameters

x1
+ tl,tr tl
+ pad_S100_100_LMTOP_BLNo_fdaf576b
* No parameters


x2
+ tl,tr tr
+ pad_S100_100_LMTOP_BLNo_fdaf576b
* No parameters


x3
+ bl,br br
+ pad_S100_100_LMTOP_BLNo_fdaf576b
* No parameters


x4
+ bl,br bl
+ pad_S100_100_LMTOP_BLNo_fdaf576b
* No parameters


x5
+ tl,tr
+ straight_L8_N2_CSmetal3_W10
* No parameters


x6
+ tl,tr
+ wire_corner_CSmetal3_RNone
* No parameters


x7
+ tl,tr
+ straight_L200_N2_CSmetal3_W10
* No parameters


x8
+ tl,tr
+ wire_corner_CSmetal3_RNone
* No parameters


x9
+ tl,tr
+ straight_L392_N2_CSmetal3_W10
* No parameters


x10
+ bl,br
+ straight_L400_N2_CSmetal3_W10
* No parameters


.ENDS
